FROM nvidia/cuda:11.6.1-cudnn8-runtime-ubuntu20.04

# ARG DEBIAN_FRONTEND=noninteractive
RUN echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null

# Install python
RUN apt-get update
# RUN apt-get upgade -y
# RUN apt-get install -y python3
# RUN apt-get install -y python3-pip
# # Update
# RUN python3 -m pip install --no-cache-dir --upgrade pip
# # Set working directory
WORKDIR /AttendenceChecker
# # Install dependencies
ADD ./requirements.txt .
# RUN pip3 install -r requirements.txt

# RUN git config --global --add safe.directory /AttendenceChecker